### ISSUE TITLE
about "from kan import KAN"

### ISSUE THREAD

**Issue by cucumber2249** [Aqasch/KANQAS_code#1]
In the KANQ.py file, there is code importing KAN from kan, but there is no kan file in the project. Could it be missing?

**Comment by Aqasch** [comment]
Hello! You are correct that the kan folders and the files were not uploaded. I just updated the github with an additional file called `kanqas.yml` which contains all the dependencies to run the code in this github without any errors. Please follow the updated README file and let me know, I will close it after I hear back from you. This issue I believe is redressed.

**Comment by cucumber2249** [comment]
The problem has been solved. Thank you for your timely response.
